In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
cpcb_2024 = pd.read_csv("../data/raw/CPCB/Raw_Data_2024_site_5792_ambazari_nagpur_mpcb_1Hr.csv")

cpcb_2024.sample(5)

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
3580,2024-05-29 04:00:00,50.66,108.04,1.35,12.47,7.60,11.02,12.89,0.16,42.47,...,1.99,32.64,46.58,1.31,304.41,0.0,0.0,0.0,NaN,NaN
1988,2024-03-23 20:00:00,79.05,181.46,26.00,118.86,82.95,44.24,10.57,2.96,0.25,...,43.39,27.87,46.38,1.08,322.37,0.0,0.0,0.0,NaN,NaN
5255,2024-08-06 23:00:00,13.42,49.87,4.61,7.12,7.42,7.71,6.06,0.44,1.79,...,5.12,24.53,94.40,0.83,86.84,0.0,0.0,0.0,NaN,NaN
740,2024-01-31 20:00:00,119.60,216.13,10.34,94.10,57.45,39.57,14.75,2.05,13.95,...,51.40,22.78,67.43,1.28,289.93,0.0,0.0,0.0,NaN,NaN
2114,2024-03-29 02:00:00,60.72,126.86,0.98,20.96,11.74,8.18,29.44,0.30,35.85,...,2.63,28.94,46.02,0.75,248.87,0.0,0.0,0.0,NaN,NaN

In [5]:
cpcb_2025 = pd.read_csv("../data/raw/CPCB/Raw_Data_2025_site_5792_ambazari_nagpur_mpcb_1Hr.csv")

cpcb_2025.sample(5)

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
6653,2025-10-05 05:00:00,14.80,41.12,1.94,7.58,5.52,9.30,8.68,0.28,9.16,...,1.60,23.86,97.22,1.04,101.60,0.0,0.0,0.00,NaN,NaN
3972,2025-06-15 12:00:00,27.12,49.88,3.14,9.45,7.46,9.90,6.99,0.34,39.89,...,1.23,36.55,50.51,1.09,164.46,0.0,0.0,201.10,NaN,NaN
6105,2025-09-12 09:00:00,13.30,26.43,4.41,6.14,6.74,14.02,10.20,0.32,13.13,...,6.69,26.51,92.75,1.32,342.01,0.0,0.0,18.78,NaN,NaN
8175,2025-12-07 15:00:00,41.20,89.80,1.56,24.68,14.14,13.09,53.67,0.28,78.25,...,0.61,25.74,34.16,0.68,93.60,0.0,0.0,99.52,NaN,NaN
6686,2025-10-06 14:00:00,35.18,73.21,NaN,NaN,NaN,17.67,10.75,0.62,10.02,...,9.37,25.83,89.12,1.22,160.76,0.0,0.0,3.40,NaN,NaN

In [9]:
weather = pd.read_csv("../data/raw/Weather/open-meteo-21.12N79.02E323m.csv", skiprows=2)

weather.sample(5)

,time,temperature_2m (°C),relative_humidity_2m (%),weather_code (wmo code),wind_speed_10m (km/h),wind_direction_10m (°)
9958,2025-02-18T22:00,26.2,36,0,7.9,311
3175,2024-05-12T07:00,31.4,57,0,4.1,142
540,2024-01-23T12:00,26.5,53,0,7.6,19
3703,2024-06-03T07:00,29.0,64,3,9.9,170
14011,2025-08-06T19:00,29.4,74,3,10.1,197

In [10]:
print("CPCB 2024:", cpcb_2024.shape)
print("CPCB 2025:", cpcb_2025.shape)
print("Weather:", weather.shape)

CPCB 2024: (8784, 25)
CPCB 2025: (8760, 25)
Weather: (17544, 6)

In [11]:
print("CPCB 2024 columns:")
print(cpcb_2024.columns.tolist())

print("\nCPCB 2025 columns:")
print(cpcb_2025.columns.tolist())

print("\nWeather columns:")
print(weather.columns.tolist())

CPCB 2024 columns:
['Timestamp', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)', 'NO2 (µg/m³)', 'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)', 'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)', 'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)', 'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)', 'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)']

CPCB 2025 columns:
['Timestamp', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)', 'NO2 (µg/m³)', 'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)', 'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)', 'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)', 'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)', 'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)']

Weather columns:
['time', 'temperature_2m (°C)', 'relative_humidity_2m (%)', 'weather_code (wmo code)', 'wind_speed_10m (km/h)', 'wind_direction_10m (°)']

In [12]:
print("CPCB 2024:")
print(cpcb_2024.dtypes)

print("\nWeather:")
print(weather.dtypes)

CPCB 2024:
Timestamp                  str
PM2.5 (µg/m³)          float64
PM10 (µg/m³)           float64
NO (µg/m³)             float64
NO2 (µg/m³)            float64
NOx (ppb)              float64
NH3 (µg/m³)            float64
SO2 (µg/m³)            float64
CO (mg/m³)             float64
Ozone (µg/m³)          float64
Benzene (µg/m³)        float64
Toluene (µg/m³)        float64
Xylene (µg/m³)         float64
O Xylene (µg/m³)       float64
Eth-Benzene (µg/m³)    float64
MP-Xylene (µg/m³)      float64
AT (°C)                float64
RH (%)                 float64
WS (m/s)               float64
WD (deg)               float64
RF (mm)                float64
TOT-RF (mm)            float64
SR (W/mt2)             float64
BP (mmHg)              float64
VWS (m/s)              float64
dtype: object

Weather:
time                            str
temperature_2m (°C)         float64
relative_humidity_2m (%)      int64
weather_code (wmo code)       int64
wind_speed_10m (km/h)       float64
wind_direction_10m (°)        int64
dtype: object

In [17]:
print("CPCB 2024 missing values:")
print(cpcb_2024.isnull().sum().sort_values(ascending=False))

CPCB 2024 missing values:
Xylene (µg/m³)         8784
BP (mmHg)              8784
VWS (m/s)              8784
O Xylene (µg/m³)       8784
Eth-Benzene (µg/m³)     229
MP-Xylene (µg/m³)       227
Ozone (µg/m³)           221
NO (µg/m³)              196
Benzene (µg/m³)         156
Toluene (µg/m³)         156
NH3 (µg/m³)             116
NO2 (µg/m³)              96
SO2 (µg/m³)              94
RH (%)                   93
NOx (ppb)                92
PM10 (µg/m³)             88
WS (m/s)                 86
RF (mm)                  84
WD (deg)                 84
SR (W/mt2)               84
AT (°C)                  84
PM2.5 (µg/m³)            77
CO (mg/m³)               77
Timestamp                 0
TOT-RF (mm)               0
dtype: int64

In [19]:
print("\nCPCB 2025 missing values:")
print(cpcb_2025.isnull().sum().sort_values(ascending=False))

CPCB 2025 missing values:
Xylene (µg/m³)         8760
BP (mmHg)              8760
VWS (m/s)              8760
O Xylene (µg/m³)       8760
Ozone (µg/m³)           261
NH3 (µg/m³)             206
NO (µg/m³)              188
Eth-Benzene (µg/m³)     182
MP-Xylene (µg/m³)       182
SO2 (µg/m³)             126
NO2 (µg/m³)             120
Toluene (µg/m³)         119
Benzene (µg/m³)         119
NOx (ppb)               105
PM2.5 (µg/m³)            93
PM10 (µg/m³)             87
CO (mg/m³)               78
RF (mm)                  64
AT (°C)                  64
RH (%)                   64
WS (m/s)                 64
SR (W/mt2)               64
WD (deg)                 64
Timestamp                 0
TOT-RF (mm)               0
dtype: int64

In [15]:
print("\nWeather missing values:")
print(weather.isnull().sum())

Weather missing values:
time                        0
temperature_2m (°C)         0
relative_humidity_2m (%)    0
weather_code (wmo code)     0
wind_speed_10m (km/h)       0
wind_direction_10m (°)      0
dtype: int64

In [ ]:
cpcb_2024[cpcb_2024["PM2.5 (µg/m³)"].isnull()][["Timestamp", "PM2.5 (µg/m³)"]].head(20)

               Timestamp  PM2.5 (µg/m³)
0    2024-01-01 00:00:00            NaN
1    2024-01-01 01:00:00            NaN
2    2024-01-01 02:00:00            NaN
3    2024-01-01 03:00:00            NaN
4    2024-01-01 04:00:00            NaN
131  2024-01-06 11:00:00            NaN
132  2024-01-06 12:00:00            NaN
145  2024-01-07 01:00:00            NaN
146  2024-01-07 02:00:00            NaN
147  2024-01-07 03:00:00            NaN
148  2024-01-07 04:00:00            NaN
149  2024-01-07 05:00:00            NaN
150  2024-01-07 06:00:00            NaN
151  2024-01-07 07:00:00            NaN
152  2024-01-07 08:00:00            NaN
153  2024-01-07 09:00:00            NaN
154  2024-01-07 10:00:00            NaN
192  2024-01-09 00:00:00            NaN
193  2024-01-09 01:00:00            NaN
194  2024-01-09 02:00:00            NaN

In [21]:
cpcb_2025[cpcb_2025["PM2.5 (µg/m³)"].isnull()][["Timestamp", "PM2.5 (µg/m³)"]].head(20)

                Timestamp  PM2.5 (µg/m³)
155   2025-01-07 11:00:00            NaN
156   2025-01-07 12:00:00            NaN
353   2025-01-15 17:00:00            NaN
354   2025-01-15 18:00:00            NaN
395   2025-01-17 11:00:00            NaN
396   2025-01-17 12:00:00            NaN
876   2025-02-06 12:00:00            NaN
877   2025-02-06 13:00:00            NaN
1019  2025-02-12 11:00:00            NaN
1020  2025-02-12 12:00:00            NaN
1472  2025-03-03 08:00:00            NaN
1571  2025-03-07 11:00:00            NaN
2133  2025-03-30 21:00:00            NaN
2134  2025-03-30 22:00:00            NaN
2188  2025-04-02 04:00:00            NaN
2242  2025-04-04 10:00:00            NaN
2316  2025-04-07 12:00:00            NaN
2535  2025-04-16 15:00:00            NaN
3039  2025-05-07 15:00:00            NaN
3040  2025-05-07 16:00:00            NaN

In [ ]:
target_pollutants = ["PM2.5 (µg/m³)","PM10 (µg/m³)","NO2 (µg/m³)","SO2 (µg/m³)","CO (mg/m³)","Ozone (µg/m³)"]

missing_2024 = cpcb_2024[target_pollutants].isnull().mean() * 100
missing_2025 = cpcb_2025[target_pollutants].isnull().mean() * 100

print("2024 Missing Percentage:")
print(missing_2024.round(2))

print("\n2025 Missing Percentage:")
print(missing_2025.round(2))

2024 Missing Percentage:
PM2.5 (µg/m³)    0.88
PM10 (µg/m³)     1.00
NO2 (µg/m³)      1.09
SO2 (µg/m³)      1.07
CO (mg/m³)       0.88
Ozone (µg/m³)    2.52
dtype: float64

2025 Missing Percentage:
PM2.5 (µg/m³)    1.06
PM10 (µg/m³)     0.99
NO2 (µg/m³)      1.37
SO2 (µg/m³)      1.44
CO (mg/m³)       0.89
Ozone (µg/m³)    2.98
dtype: float64

In [24]:
print("CPCB 2024 duplicate timestamps:",
      cpcb_2024["Timestamp"].duplicated().sum())

print("CPCB 2025 duplicate timestamps:",
      cpcb_2025["Timestamp"].duplicated().sum())

print("Weather duplicate timestamps:",
      weather["time"].duplicated().sum())

CPCB 2024 duplicate timestamps: 0
CPCB 2025 duplicate timestamps: 0
Weather duplicate timestamps: 0

In [26]:
cpcb_2024["Timestamp"] = pd.to_datetime(cpcb_2024["Timestamp"])
cpcb_2025["Timestamp"] = pd.to_datetime(cpcb_2025["Timestamp"])
weather["time"] = pd.to_datetime(weather["time"])

print(cpcb_2024["Timestamp"].dtype)
print(cpcb_2025["Timestamp"].dtype)
print(weather["time"].dtype)

datetime64[us]
datetime64[us]
datetime64[us]

In [27]:
print("CPCB 2024:")
print(cpcb_2024["Timestamp"].min())
print(cpcb_2024["Timestamp"].max())

print("\nCPCB 2025:")
print(cpcb_2025["Timestamp"].min())
print(cpcb_2025["Timestamp"].max())

print("\nWeather:")
print(weather["time"].min())
print(weather["time"].max())

CPCB 2024:
2024-01-01 00:00:00
2024-12-31 23:00:00

CPCB 2025:
2025-01-01 00:00:00
2025-12-31 23:00:00

Weather:
2024-01-01 00:00:00
2025-12-31 23:00:00